# ----------------------------------------------------------------------------
#
# Package             : pyramid_debugtoolbar
# Source Repo         : https://github.com/Pylons/pyramid_debugtoolbar
# Travis Job Link     : https://travis-ci.com/github/asellappen/pyramid_debugtoolbar/
# Created travis.yml  : Yes
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

language: python
sudo: false

matrix:
  include:
    - python: 3.7
      env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=flake8
      arch: ppc64le


install:
  - travis_retry pip install tox
  - pip install flake8
  - pip install pytest-flake8
script:
  - pytest --flake8

notifications:
  email:
    - asellappen@yahoo.com
